print('"Commands"\t"Description"')
print('--------------\t--------------')
print('"INTRODUCE"\tGives PyPA introduction.')
print('"DAY"\t\tDisplay day.')
print('"DATE"\t\tDisplay date.')
print('"TIME"\t\tDisplay time.')
print('"KILL"\t\tHelps you to kill task.')
print('"MANUAL"\tDisplays manual of different apllication.')
print('"SOLVE"\t\tHelps in calculation.')
print('"WEATHER"\tDisplays current weather status.') 
print('"NEW MAIL"\tShows new received emails.')
print('"SEND EMAIL"\tSends E-mail.')
print('"PC INFO"\tDisplays Computer hardware information.')
print('"DICT"\t\tOpens dictionary.')
print('"WIKI"\t\tOpens Wikipedia.')
print('"POST A STATUS"\tPost status on Facebook.')
print('"UPLOAD A PICT"\tUploads picture on Facebook.')
print('"MOVIE"\t\tDisplays movies information from IMDb.')
print('"UPGRADE"\tUpdate/Upgrades your PC.')
print('"CACHE"\t\tCleans your RAM\'s cache.')
print('Press Ctrl+C to close PyPA.')
