print('PyPA \nVersion:1.1.0')
print('Hello, I am PyPA. I am command line based personal assistant.')

print('I can : ')
print('Tell time, date and day.')
print('Find meanings of words.')
print('Tell current weather.')
print('Kill process.')
print('Search information on wikipedia.')
print('Solve maths for you.')
print('Upload Pictures or Status on Facebook.')
print('Display PC details.')
print('Receive/Send E-mails.')
print('Update/Upgrade your OS.')
print('Display manuals of different apps.')
print('Search movies info in IMDb.')
print('Clear RAM\'s cache.')
print('''\nDevelopers: \n\tSabin Ranabhat\n\tRoshan Kunwar\n\tSandeep Tiwari\n\tRakesh Mandal''')
